#!/bin/sh
# vim: set ts=4:
set -eu

cd "$(dirname "$0")/.."
. script/bootstrap


einfo 'Running linter'
python3 -m pycodestyle

einfo 'Checking types'
python3 -m mypy --check-untyped-defs --silent-imports *.py
cat >&2 <<-EOF

	NOTE: Since we currently don't have stub files for the dependencies
	it basically checks only types from the stdlib!
EOF
