#!/bin/bash
# vim: set ts=4:
set -eu -o pipefail

cd "$(dirname "$0")/.."
source script/bootstrap

echo -e '\n==> Checking types...'
$PYTHON -m mypy --check-untyped-defs --silent-imports *.py
cat <<-EOF >&2

	NOTE: Since we currently don't have stub files for the dependencies
	it basically checks only types from the stdlib!
EOF

echo -e '\n==> Running linter...'
$PYTHON -m pycodestyle
